### ISSUE TITLE
Error react-native 0.33.1

### ISSUE THREAD

**Issue by remch1990** [joonhocho/react-native-linkedin-sdk#1]
App/node_modules/react-native-linkedin-sdk/index.js: Unexpected token, expected ; (1:20) at index.js:1:20

**Comment by TomAtterton** [comment]
I am currently having the same issue, with react-native 0.40.0

**Comment by joonhocho** [comment]
@remch1990 @TomAtterton https://github.com/joonhocho/react-native-google-sign-in/issues/1.

**Comment by joonhocho** [comment]
@remch1990 @TomAtterton I changed `import` and `export` statements to `require` and `module.exports`, so it should be fixed now.
