### ISSUE TITLE
Cannot read property 'configure' of undefined

### ISSUE THREAD

**Issue by ranpaco** [joonhocho/react-native-linkedin-sdk#2]
Hi, I'm try to run you library on iOS but I get this error:

> Cannot read property 'configure' of undefined
> TypeError: Cannot read property 'configure' of undefined

For I can see RNLinkedInSessionManager is undefined in LinkedInSessionManager.ios.js 

I try to follow all step but I thinks that I missing something

any help would be appreciated.

**Comment by joonhocho** [comment]
@ranpaco which version of react-native are you using?

**Comment by connexa** [comment]
<= 0.39

**Comment by joonhocho** [comment]
@ranpaco @connexa I've updated iOS installation instructions on README.md. I've missed few things. I also added ExampleApp to repo, so please check it out if you think you are missing something.
I've only tested with v0.40, but supporting 0.39 shouldn't be a problem. Maybe few header files needs to be adjusted if any.

**Comment by joonhocho** [comment]
@ranpaco @connexa Closing this issue as I believe it's fixed now. Feel free to reopen it if you find it otherwise.

**Comment by bethqiang** [comment]
I know this has been closed, but currently facing the same issue (on React Native v 0.43.0) and have no idea why... @ranpaco @connexa did you ever get this resolved? (And I did try the solution in #8 ...)

Can open a new issue if needed.

**Comment by freework-tech** [comment]
I have the same issue. Did someone find a solution?
